
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app
spec:
  selector:
    matchLabels:
      name: voting-app
  replicas : 2
  template:
    metadata:
      labels:
        name: voting-app
    spec:
      containers:
      - name: voting-app
        image: kodekloud/examplevotingapp_vote:v1
        ports:
          - containerPort: 80
            name: voting-app
