
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
spec:
  selector:
    matchLabels:
      name: result-app
  replicas: 1
  template:
    metadata:
      labels:
        name: result-app
    spec:
      containers:
      - name: result-app
        image: mina1402/examplevotingapp_result:v4
        ports:
          - containerPort: 80
            name: result-app
